# Generated by Django 2.2.4 on 2019-09-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20190831_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_tags',
            field=models.ManyToManyField(to='entries.Tag'),
        ),
    ]
