# Generated by Django 2.2.4 on 2019-09-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20190903_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='entries',
            field=models.ManyToManyField(to='entries.Entry'),
        ),
    ]
