# Generated by Django 2.2.4 on 2019-09-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20190903_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_tags',
            field=models.ManyToManyField(to='entries.Tag'),
        ),
    ]
